import { config } from "../config/config.js";

export const incidentAlertTemplate = (incident, companyName) => `
  <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee;">
    <h2 style="color: #d9534f;">🚨 New Incident Detected: ${incident.title}</h2>
    <p><strong>Company:</strong> ${companyName}</p>
    <p><strong>Severity:</strong> <span style="text-transform: uppercase; font-weight: bold;">${incident.severity}</span></p>
    <p><strong>Affected Services:</strong> ${incident.affectedServices.join(', ')}</p>
    <hr />
    <p><strong>Description:</strong></p>
    <p>${incident.description}</p>
    <br />
    <a href="${config.CLIENT_URL}/incidents/${incident._id}" 
       style="background: #0275d8; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
       View Incident Dashboard
    </a>
    <p style="margin-top: 20px; font-size: 12px; color: #888;">This incident was automatically generated by Smart Response AI Monitoring.</p>
  </div>
`;
